const app = document.querySelector('#app');
const art={
  clock:'<circle cx="32" cy="31" r="23" fill="#e5d6b5" stroke="#765a40" stroke-width="5"/><circle cx="32" cy="31" r="17" fill="none" stroke="#a79573" stroke-width="1"/><path d="M32 16v15l10 6" fill="none" stroke="#3d4840" stroke-width="3" stroke-linecap="round"/><circle cx="32" cy="31" r="2.5" fill="#b76140"/>',
  washer:'<rect x="8" y="5" width="48" height="55" rx="5" fill="#b5c4bc" stroke="#455957" stroke-width="3"/><rect x="13" y="11" width="38" height="9" rx="2" fill="#899e96"/><circle cx="32" cy="40" r="14" fill="#617d7b" stroke="#e1dfc9" stroke-width="4"/><path d="M23 42c6-11 16 11 20-4" fill="none" stroke="#d8c291" stroke-width="2"/>',
  plant:'<path d="M30 35C9 34 12 18 13 15c13 0 21 7 19 20M34 32c-2-18 10-25 20-26 3 13-3 24-18 30M32 39C15 29 5 35 6 45c8 9 18 7 26-1m4-4c15-10 22-4 21 5-8 9-17 7-23-1" fill="#8ca187" stroke="#d1c794" stroke-width="2"/><path d="M17 41h31l-4 19H21z" fill="#bd7154" stroke="#734b3b" stroke-width="2"/>',
  radio:'<rect x="7" y="15" width="50" height="37" rx="5" fill="#c87953" stroke="#654936" stroke-width="3"/><path d="M18 15 42 3" stroke="#d3c8a8" stroke-width="2"/><circle cx="18" cy="29" r="3" fill="#f0ddaa"/><circle cx="27" cy="29" r="3" fill="#f0ddaa"/><path d="M14 39h25m-25 4h25" stroke="#693f32" stroke-width="2"/><circle cx="48" cy="40" r="5" fill="#e2cc9d" stroke="#693f32" stroke-width="2"/>',
  basket:'<path d="M8 27h48l-5 31H13z" fill="#bf8b60" stroke="#624a38" stroke-width="3"/><path d="M17 27c0-23 29-23 30 0" fill="none" stroke="#e0bd8d" stroke-width="4"/><path d="M16 39h34M15 48h33" stroke="#906846" stroke-width="2"/><path d="M23 27v30m18-30v30" stroke="#d5a876" stroke-width="2"/>',
  window:'<rect x="8" y="5" width="48" height="53" fill="#87a69b" stroke="#654f3e" stroke-width="5"/><path d="M32 7v49M10 31h44" stroke="#654f3e" stroke-width="4"/><path d="M13 12h16v16H13zM36 12h15v16H36z" fill="#c3cba5" opacity=".45"/>',
  menu:'<path d="M10 7h44v52H10z" fill="#dfd2ae" stroke="#624c37" stroke-width="3"/><path d="M18 18h27m-27 8h22m-22 9h26m-26 9h18" stroke="#88745a" stroke-width="2"/><path d="M21 13h22" stroke="#b35c40" stroke-width="3"/>',
  cup:'<path d="M13 17h33l-3 38H17z" fill="#cc8060" stroke="#684b3c" stroke-width="3"/><path d="M46 24h7c8 0 8 16 0 16h-8" fill="none" stroke="#684b3c" stroke-width="4"/><path d="M21 11c-5-6 4-8 0-13m12 13c-5-6 4-8 0-13" fill="none" stroke="#e9d8bb" stroke-width="2"/>',
  stool:'<path d="M10 20h44l-5 9H15z" fill="#c45f46" stroke="#6c4035" stroke-width="3"/><path d="m19 29-5 30m29-30 5 30M27 30v25m13-25v25" stroke="#725341" stroke-width="4"/>',
  jukebox:'<path d="M13 58V23C13 5 51 5 51 23v35z" fill="#bd674c" stroke="#5d4434" stroke-width="3"/><path d="M19 24c0-13 26-13 26 0v7H19z" fill="#e4d39f" stroke="#704b36" stroke-width="2"/><path d="M20 39h24m-24 6h24m-24 6h24" stroke="#e4d39f" stroke-width="2"/><circle cx="32" cy="24" r="4" fill="#82a091"/>',
  bell:'<path d="M15 45h34l-5-6V27c0-16-22-16-22 0v12z" fill="#d1a85e" stroke="#705238" stroke-width="3"/><path d="M26 49c1 10 11 10 12 0" fill="#b47c42" stroke="#705238" stroke-width="2"/><circle cx="32" cy="17" r="3" fill="#f3dca8"/>',
  door:'<path d="M12 58V9l38-4v53z" fill="#9a6748" stroke="#533f32" stroke-width="3"/><path d="m18 14 26-3v42l-26 2z" fill="#b17b55"/><circle cx="39" cy="35" r="2.5" fill="#e0be7f"/><rect x="22" y="18" width="17" height="10" rx="2" fill="#e5d8b8"/><text x="30.5" y="26" text-anchor="middle" font-size="7" font-family="monospace" fill="#4e5144">3B</text>',
  phone:'<path d="M10 18c-5-8 6-14 12-9l8 9-7 8c3 7 8 12 15 15l8-7 9 8c5 6-1 17-9 14C24 49 12 36 10 18z" fill="#d1c8ad" stroke="#5a5042" stroke-width="3"/><circle cx="47" cy="47" r="3" fill="#b96042"/>',
  mirror:'<rect x="12" y="5" width="40" height="55" rx="18" fill="#94aaa3" stroke="#725d47" stroke-width="4"/><path d="M21 21c5-10 14-11 21-4" fill="none" stroke="#d7e1d2" stroke-width="3" opacity=".8"/><path d="M26 61v5m12-5v5m-17 0h23" stroke="#725d47" stroke-width="3"/>',
  keys:'<circle cx="20" cy="22" r="10" fill="none" stroke="#d9b570" stroke-width="5"/><path d="m28 28 25 25m-9-9 5-5m-12-2 5-5" stroke="#d9b570" stroke-width="5" stroke-linecap="round"/>',
  lamp:'<path d="M15 27h35L44 8H22z" fill="#d1b16d" stroke="#5e4e3b" stroke-width="3"/><path d="M32 27v25m-9 7h19l-10-7z" fill="#ae7954" stroke="#5e4e3b" stroke-width="3"/><path d="M22 31 12 47m34-16 9 16" stroke="#e7d6a2" stroke-width="2" opacity=".5"/>',
  sign:'<path d="M12 15h40v38H12z" fill="#cf6546" stroke="#543f32" stroke-width="4"/><text x="32" y="40" text-anchor="middle" font-size="10" font-weight="bold" font-family="monospace" fill="#fff0cf">OPEN</text>',
  apple:'<path d="M32 20c-12-11-25-2-22 14 3 19 13 28 22 20 9 8 19-1 22-20 3-16-10-25-22-14z" fill="#a5ac69" stroke="#5b6045" stroke-width="3"/><path d="M32 21c-2-9 2-14 9-16m-4 3c7-2 11 0 13 4" fill="none" stroke="#52634b" stroke-width="4"/><path d="M16 34h8" stroke="#d7d399" stroke-width="3"/>',
  register:'<path d="M10 22h45v34H10z" fill="#788c7d" stroke="#424b40" stroke-width="3"/><path d="M17 13h31v11H17z" fill="#d4cca9" stroke="#424b40" stroke-width="3"/><circle cx="23" cy="18" r="2" fill="#aa5a42"/><path d="M15 33h35v6H15zm5 12h25v7H20z" fill="#b8b69a"/>',
  shelf:'<path d="M12 7h40v53H12z" fill="#795940" stroke="#493d30" stroke-width="3"/><path d="M14 25h36M14 43h36" stroke="#d2ad7a" stroke-width="4"/><path d="M17 11h8v12h-8zm12 0h8v12h-8zm11 0h7v12h-7zm-22 18h9v12h-9zm13 0h8v12h-8zm11 0h7v12h-7zm-21 18h10v12H21zm14 0h12v12H35z" fill="#9d7460" stroke="#e1cfaa" stroke-width="1"/>',
  fish:'<rect x="6" y="7" width="52" height="49" rx="4" fill="#95b6ad" stroke="#5c6454" stroke-width="4"/><path d="M12 42h40v10H12z" fill="#b3a278"/><path d="M21 33c8-11 19-10 25 0-6 10-17 11-25 0zm-1 0-8-7v14z" fill="#cf9958" stroke="#725c43" stroke-width="2"/><circle cx="40" cy="31" r="1.5" fill="#29372f"/><path d="M18 46c4-7 7-8 10-8m10 8 8-6" fill="none" stroke="#77947f" stroke-width="2"/>',
  magazine:'<path d="M12 8h40v52H12z" fill="#d0bb91" stroke="#604b37" stroke-width="3"/><path d="M16 13h32v21H16z" fill="#71857b"/><circle cx="32" cy="23" r="7" fill="#e0bd79"/><path d="M17 41h28m-28 6h24m-24 6h18" stroke="#79664b" stroke-width="2"/>',
  chair:'<path d="M15 10h34v32H15z" fill="#637c7e" stroke="#424b47" stroke-width="3"/><path d="M11 37h42v9H11z" fill="#728987" stroke="#424b47" stroke-width="3"/><path d="m17 46-3 14m36-14 3 14" stroke="#6d5944" stroke-width="4"/>',
  vent:'<rect x="7" y="15" width="50" height="35" rx="3" fill="#bbb9a7" stroke="#635d4f" stroke-width="3"/><path d="M14 22h36m-36 7h36m-36 7h36m-36 7h36" stroke="#777669" stroke-width="3"/>',
  painting:'<rect x="7" y="7" width="50" height="51" fill="#9a7551" stroke="#594533" stroke-width="4"/><rect x="13" y="13" width="38" height="39" fill="#81a19b"/><path d="m13 42 11-12 9 9 6-8 12 12v9H13z" fill="#d8c18b"/><path d="M13 48h38" stroke="#c9d9ca" stroke-width="2"/>',
};
function draw(id){return `<svg viewBox="0 0 64 68" aria-hidden="true">${art[id]||'<circle cx="32" cy="32" r="23" fill="#cbb58b"/>'}</svg>`}
const positions = {clock:[20,34],washer:[44,57],plant:[80,65],radio:[63,36],basket:[34,76],window:[77,38],menu:[22,38],cup:[45,69],stool:[69,69],jukebox:[82,69],bell:[54,42],door:[21,56],phone:[47,67],mirror:[53,34],keys:[78,72],lamp:[75,46],sign:[48,29],apple:[70,67],register:[35,68],shelf:[80,50],fish:[51,56],magazine:[26,68],chair:[75,70],vent:[25,38],painting:[54,39]};
const state = {room:null,playerId:null,code:null,tab:'home',error:'',inspected:null,toast:'',lastKey:'',timer:null,poll:null,name:''};
const esc = value => String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const storageKey = code => `odd-hours:${code}`;
function toast(message){state.toast=message;document.querySelector('.toast')?.remove();const el=document.createElement('div');el.className='toast';el.textContent=message;document.body.append(el);setTimeout(()=>el.remove(),2200)}
function setError(text=''){state.error=text;const el=document.querySelector('.error');if(el)el.textContent=text;}
async function request(url,method='GET',data={}){
  const options={method,headers:{'content-type':'application/json'}};
  if(method==='GET'){const q=new URLSearchParams({playerId:state.playerId||''});url+=`?${q}`;}else options.body=JSON.stringify(data);
  const response=await fetch(url,options);const payload=await response.json();if(!response.ok)throw new Error(payload.error||'Something went wrong.');return payload;
}
async function createRoom(name){state.name=name;setError();try{const result=await request('/api/rooms','POST',{name});state.playerId=result.playerId;state.code=result.room.code;localStorage.setItem(storageKey(state.code),state.playerId);history.replaceState(null,'',`#${state.code}`);acceptRoom(result.room,true);}catch(e){setError(e.message)}}
async function joinRoom(code,name){state.name=name;setError();try{code=code.trim().toUpperCase();const key=storageKey(code);const prior=localStorage.getItem(key);const response=await fetch(`/api/rooms/${encodeURIComponent(code)}/join`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name,playerId:prior})});const result=await response.json();if(!response.ok)throw new Error(result.error);state.playerId=result.playerId;state.code=code;localStorage.setItem(key,state.playerId);history.replaceState(null,'',`#${code}`);acceptRoom(result.room,true);}catch(e){setError(e.message)}}
function acceptRoom(room,force=false){state.room=room;state.tab=room.status==='lobby'?'lobby':room.status==='finished'?'finished':'game';state.error='';const key=JSON.stringify([room.status,room.roundNumber,room.players,room.scores,room.votes,room.votedFor,room.winningChoice,room.answer,room.view]);if(force||key!==state.lastKey){state.lastKey=key;render();}startTicker();}
function startTicker(){if(state.poll)clearInterval(state.poll);if(!state.code)return;state.poll=setInterval(async()=>{try{const r=await request(`/api/rooms/${state.code}/state`);acceptRoom(r.room);}catch{}},800);}
function startTickerOnly(){if(state.timer)clearInterval(state.timer);state.timer=setInterval(updateClock,200);}
function updateClock(){const node=document.querySelector('[data-clock]');if(!node||!state.room?.endsAt)return;const left=Math.max(0,state.room.endsAt-Date.now());const seconds=Math.ceil(left/1000);node.textContent=`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;node.classList.toggle('urgent',seconds<=10);}
function render(){if(!state.room){renderHome();return}if(state.room.status==='lobby'){renderLobby();return}if(state.room.status==='finished'){renderFinished();return}if(state.room.status==='reveal'){renderReveal();return}renderGame();}
function renderHome(){state.tab='home';const code=(location.hash||'').slice(1).toUpperCase();app.innerHTML=`<section class="hero"><div class="hero-copy"><div class="eyebrow">A cooperative game for 2–6 players</div><h1>Something is<br>slightly off.</h1><p class="lead">Step into strange everyday places. Compare what you notice. Find the one detail that shouldn’t be there before the clock runs out.</p><button class="btn" data-scroll>Gather your people <span aria-hidden="true">↗</span></button></div><div class="hero-art"><div class="moon"></div><div class="window-frame"></div><div class="wall-clock">11:58</div><div class="table"></div><div class="cup"></div><div class="art-caption">The house is open · 11:58 PM</div></div></section><section class="how"><div class="step"><span class="step-num">01</span><div><h3>Make a room</h3><p>Start a private game and share the room code. No accounts, no downloads.</p></div></div><div class="step"><span class="step-num">02</span><div><h3>Look a little closer</h3><p>Everyone sees the same place, though a few details may differ for each of you.</p></div></div><div class="step"><span class="step-num">03</span><div><h3>Talk it out</h3><p>Trade observations, vote for the odd detail, and see who had the sharpest eye.</p></div></div></section><section class="entry-grid" id="entry"><div class="panel"><div class="eyebrow">Start a new game</div><h3 class="serif">Host a room</h3><p class="muted">You'll get a code to share with your friends.</p><label class="field-label" for="host-name">Your name</label><input id="host-name" maxlength="18" placeholder="e.g. Mothman" autocomplete="nickname"><button class="btn full" data-action="create">Create a room <span>→</span></button><p class="error" data-error></p></div><div class="panel dark"><div class="eyebrow" style="color:#d99573">Join your friends</div><h3 class="serif">Enter the room</h3><p class="muted">Type the code your host shared with you.</p><label class="field-label" for="join-name">Your name</label><input id="join-name" maxlength="18" placeholder="e.g. Night Owl" autocomplete="nickname"><label class="field-label" for="room-code">Room code</label><input id="room-code" class="code-input" maxlength="6" placeholder="ABC123" value="${esc(code)}" autocomplete="off"><button class="btn full" data-action="join">Join the room <span>→</span></button><p class="error" data-error></p></div></section>`;}
function playerRows({score=false}={}){const players=state.room.players;return players.map(p=>`<div class="player-row"><span class="avatar">${esc(p.name.slice(0,1).toUpperCase())}</span><span class="player-name">${esc(p.name)} ${p.id===state.playerId?'<span class="you-tag">YOU</span>':''}</span>${p.id===state.room.hostId?'<span class="host-tag">HOST</span>':''}${score?`<strong class="score-points">${state.room.scores.find(s=>s.id===p.id)?.score||0}</strong>`:`<span class="host-tag">${p.online?'HERE':'AWAY'}</span>`}</div>`).join('');}
function shareBox(){return `<div class="room-code" data-copy role="button" tabindex="0"><small>ROOM CODE · TAP TO COPY</small><strong>${esc(state.room.code)}</strong><em>share this link or code ↗</em></div>`;}
function renderLobby(){const isHost=state.playerId===state.room.hostId;app.innerHTML=`<div class="eyebrow">Your private room · ${state.room.players.length} / 6 players</div><div class="lobby-head"><div><h2>Gather at the threshold.</h2><p class="muted">Share the code. The host starts when everyone's here.</p></div>${shareBox()}</div><div class="lobby-layout"><section><div class="player-list">${playerRows()}</div>${isHost?`<button class="btn full" data-action="start" ${state.room.players.length<2?'disabled':''}>Start the five-round match <span>→</span></button>${state.room.players.length<2?'<p class="muted" style="font-size:11px;text-align:center">At least one other player is needed.</p>':''}`:`<div class="panel" style="margin-top:15px;text-align:center"><span class="empty-icon">◌</span><p class="muted" style="margin:8px 0 0;font-size:12px">Waiting for the host to begin…</p></div>`}<p class="error" data-error></p></section><aside class="rules-card"><div class="eyebrow">How to play</div><ol><li>Explore the room and tap objects to inspect their details.</li><li>Tell each other what you noticed. A few details differ by player.</li><li>Vote for the exact object you think is wrong.</li><li>Correct votes score points. The top score after five rooms wins.</li></ol><span class="host-tag">45 SECONDS PER ROOM · NO LOGIN</span></aside></div>`;}
function renderGame(){const r=state.room;const view=r.view;if(!view)return;const isLocked=Boolean(r.votedFor);app.innerHTML=`<div class="room-screen"><section class="game-main"><div class="round-head"><div><div class="round-count">ROOM ${String(r.roundNumber).padStart(2,'0')} <span style="color:#b4aa92">/ 05</span></div><h2 style="margin:5px 0 0">${esc(view.name)}</h2></div><div class="timer" data-clock>00:45</div></div><div class="scene ${esc(view.sky)}"><div class="scene-title">ODD HOURS · ${esc(view.name)}</div><div class="scene-glow"></div><div class="scene-window"></div>${view.objects.map((o,i)=>{const xy=positions[o.id]||[25+i*10,55];return `<button class="object ${o.changed?'odd':''} ${state.inspected===o.id?'selected':''}" style="--x:${xy[0]}%;--y:${xy[1]}%" data-inspect="${esc(o.id)}" aria-label="Inspect ${esc(o.label)}"><span class="glyph">${draw(o.id)}</span><span class="obj-label">${esc(o.label)}</span></button>`}).join('')}<div class="scene-subtitle">${esc(view.subtitle)}</div><div class="scene-object-info ${state.inspected?'':'hidden'}" data-detail>${(()=>{const obj=view.objects.find(o=>o.id===state.inspected);return obj?`<strong>${esc(obj.label)}</strong>${esc(obj.detail)}`:''})()}</div></div><p class="scene-hint">Tap or click an object to inspect it. Say what you notice out loud.</p></section><aside class="vote-panel"><div class="eyebrow">Your private vote</div><h3>What feels out of place?</h3><p>Choose the exact object. Your vote stays private until the room is revealed.</p><div class="choices">${view.objects.map(o=>`<button class="choice ${r.votedFor===o.id?'active':''}" data-vote="${esc(o.id)}" ${isLocked?'disabled':''}><span>${esc(o.label)}</span>${r.votedFor===o.id?'<span class="check">✓</span>':''}</button>`).join('')}</div><div class="vote-status">${isLocked?'VOTE LOCKED · NICE EYE':`${r.players.filter(p=>p.hasVoted).length} OF ${r.players.length} VOTED`}</div><div class="roster">${r.players.map(p=>`<div class="roster-row"><span>${esc(p.name)}${p.id===state.playerId?' (you)':''}</span><span class="state ${p.hasVoted?'done':''}">${p.hasVoted?'READY':'LOOKING'}</span></div>`).join('')}</div></aside></div>`;updateClock();}
function renderReveal(){const r=state.room;const correctId=({ 'The Laundromat':'clock','The Night Diner':'menu','Apartment 3B':'door','The Corner Shop':'sign','The Waiting Room':'fish'})[r.view?.name];const winner=r.winningChoice===correctId;const voteCounts={};Object.values(r.votes).forEach(v=>{if(v)voteCounts[v]=(voteCounts[v]||0)+1});const byName=Object.fromEntries(r.view.objects.map(o=>[o.id,o.label]));app.innerHTML=`<div class="results-layout"><section><div class="eyebrow">Room ${String(r.roundNumber).padStart(2,'0')} · ${r.roundNumber<5?'A fresh room is opening…':'Last room complete'}</div><h2>${winner?'You found the strange thing.':'The room keeps its secret.'}</h2><div class="answer-card"><div class="result-badge">THE DETAIL THAT WASN’T RIGHT</div><div class="answer-object">${esc(r.answer?.object||'Unknown object')}</div><p>${esc(r.answer?.detail||'The room has gone quiet.')}</p></div><div class="vote-breakdown"><div class="eyebrow">The room's vote</div>${Object.entries(voteCounts).sort((a,b)=>b[1]-a[1]).map(([id,count])=>`<div class="break-row"><span>${esc(byName[id]||'No answer')}${id===r.winningChoice?' · group choice':''}</span><span>${count} ${count===1?'vote':'votes'}</span></div>`).join('')||'<p class="muted">No votes this round.</p>'}</div></section><aside class="scoreboard"><div class="eyebrow">After ${r.roundNumber} ${r.roundNumber===1?'round':'rounds'}</div><h3 class="serif">Sharp eyes</h3>${[...r.scores].sort((a,b)=>b.score-a.score).map((s,i)=>`<div class="score-row"><span class="score-rank">0${i+1}</span><span class="score-name">${esc(s.name)}${s.id===state.playerId?' · you':''}</span><strong class="score-points">${s.score}</strong></div>`).join('')}<p class="muted" style="font-size:10px;margin:12px 0 0">One point for every correct personal vote.</p></aside></div>`;}
function renderFinished(){const scores=[...state.room.scores].sort((a,b)=>b.score-a.score);const winners=scores.filter(s=>s.score===scores[0]?.score);app.innerHTML=`<section class="finale"><div class="trophy">✳</div><div class="eyebrow">The night has settled</div><h1>${winners.length===1?`${esc(winners[0].name)} saw it coming.`:'A tie in the strange hours.'}</h1><p class="muted">${winners.length===1?'Sharpest eyes in the room.':`${winners.map(w=>esc(w.name)).join(' and ')} share the win.`}</p><div class="scoreboard"><div class="eyebrow">Final scores</div><h3 class="serif">The watchful</h3>${scores.map((s,i)=>`<div class="score-row"><span class="score-rank">0${i+1}</span><span class="score-name">${esc(s.name)}</span><strong class="score-points">${s.score}</strong></div>`).join('')}</div>${state.playerId===state.room.hostId?'<button class="btn" data-action="reset">Play another match <span>→</span></button>':'<p class="muted">Ask your host to start another match.</p>'}</section>`;}
async function action(name,button){try{if(name==='create'){const input=document.querySelector('#host-name');if(!input.value.trim())return setError('Add your name first.');await createRoom(input.value.trim());}if(name==='join'){const n=document.querySelector('#join-name').value.trim();const c=document.querySelector('#room-code').value.trim();if(!n||!c)return setError('Add your name and the room code.');await joinRoom(c,n);}if(name==='start'){button.disabled=true;const r=await request(`/api/rooms/${state.code}/start`,'POST',{playerId:state.playerId});acceptRoom(r.room,true);}if(name==='reset'){button.disabled=true;const r=await request(`/api/rooms/${state.code}/reset`,'POST',{playerId:state.playerId});acceptRoom(r.room,true);}}catch(e){setError(e.message);if(button)button.disabled=false}}
document.addEventListener('click',async event=>{const actionButton=event.target.closest('[data-action]');if(actionButton){event.preventDefault();await action(actionButton.dataset.action,actionButton);return}if(event.target.closest('[data-scroll]')){document.querySelector('#entry')?.scrollIntoView({behavior:'smooth'});return}const copy=event.target.closest('[data-copy]');if(copy){try{await navigator.clipboard.writeText(`${location.origin}/#${state.room.code}`);toast('Room link copied.');}catch{toast(`Room code: ${state.room.code}`)}return}const inspect=event.target.closest('[data-inspect]');if(inspect){state.inspected=state.inspected===inspect.dataset.inspect?null:inspect.dataset.inspect;const key=state.lastKey;state.lastKey='';renderGame();state.lastKey=key;return}const vote=event.target.closest('[data-vote]');if(vote){if(vote.disabled)return;vote.disabled=true;try{const r=await request(`/api/rooms/${state.code}/vote`,'POST',{playerId:state.playerId,choice:vote.dataset.vote});acceptRoom(r.room,true);}catch(e){toast(e.message);vote.disabled=false}}});
document.addEventListener('keydown',event=>{if((event.key==='Enter'||event.key===' ')&&event.target.matches('[data-copy]'))event.target.click();});
document.addEventListener('input',event=>{if(event.target.id==='room-code')event.target.value=event.target.value.toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,6)});
async function boot(){const code=(location.hash||'').slice(1).toUpperCase();if(code){const saved=localStorage.getItem(storageKey(code));if(saved){state.playerId=saved;state.code=code;try{const result=await fetch(`/api/rooms/${encodeURIComponent(code)}/join`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({playerId:saved})});const data=await result.json();if(result.ok){state.playerId=data.playerId;acceptRoom(data.room,true);return}}catch{}}}
  renderHome();if(code){const box=document.querySelector('#room-code');if(box)box.value=code;document.querySelector('#entry')?.scrollIntoView({behavior:'smooth'});}}
boot();startTickerOnly();
